### ISSUE TITLE
3.0.0 on NuGet

### ISSUE THREAD

**Issue by ProgramFOX** [vtortola/WebSocketListener#101]
Hey!

The current NuGet version is 2.2.2, which doesn't work with .NET Standard. Could you please push the 3.0.0 version to NuGet?

Thanks in advance!

**Comment by vtortola** [comment]
Hi, I did not have time to test 3.0 properly yet, and I think I need to publish two different packages (once for .NET and other for Core). I will do hopefully in the next weeks.

**Comment by StefH** [comment]
As temporary workaround, you can use this MyGet URL: https://www.myget.org/F/websocketlistener/api/v3/index.json

@vtortola The current 3.0 version (which includes .NET and Core) is still build using the VS2015 project.json structure.

However, now VS2017 is released, we should migrate the whole project to VS2017.

Also we can restructure the source code (make the new VS2017 projects the main projects) and let these projects build for .NET 4.5, UAP and NETStandard 1.3

Let me know if you need help with this.

**Comment by Rohansi** [comment]
Any progress on this?

**Comment by StefH** [comment]
I've created an another issue : https://github.com/vtortola/WebSocketListener/issues/109 to track this.
