### ISSUE TITLE
Question: Works with SignalR & OWIN self host ?

### ISSUE THREAD

**Issue by chandotnet** [vtortola/WebSocketListener#103]
I already have a web server service hosted using OWIN self host method listening on a custom port (10088). I have registred SignalR with it but its only working with the long pooling method (probably because it's hosted on Windows Server 2008).

Now I need to find a way to enable signalR the websocket way and my question is can I use that WebSocketListener and implement it with OWIN easily ? so it will work even if hosted on an old OS ?

**Comment by vtortola** [comment]
TBH I have never tried. I you come up with anything please share.
