### ISSUE TITLE
Question : Running inside Service Fabric Cluster ( Azure )

### ISSUE THREAD

**Issue by tanwarsatya** [vtortola/WebSocketListener#107]
Is it possible to host the Websocket server in azure , What is the scaling mechanism and how will it handle sessions in case of multiple server.  Looking to host this with Service Fabric cluster.

Regards
Satya

**Comment by vtortola** [comment]
Hi!

Sorry I totally missed this post. Yes, it should be possible by just mapping the desired port, like any other TCP Service. 

This is a WebSocket component, it only provides transport, so it does not handle sessions, that is an implementation detail you should work out (using cookies for example).

Cheers.
