### ISSUE TITLE
Trying to use WebSocket in UWP app

### ISSUE THREAD

**Issue by willrbaar** [vtortola/WebSocketListener#108]
I tried to reference Vtortola Websocket in a UWP app, and I tried to download it through NuGet.  The UWP app wouldn't accept the Websocket.  Anyone know how to do this?  You said in your write up that Vtortola supports UWP.

**Comment by vtortola** [comment]
Hi. I don't think I ever mentioned UWP :) Never tried to do such thing, if you find the way please share.

**Comment by willrbaar** [comment]
On your webpage you have this statement. -- "It supports .NET Framework 4.5 and up, NETStandard 1.3 and up and Universal Windows Platform 10 (uap10.0)."  I would suggest that you take out the UWP portion.  If I come up with something I'll let you know.

**Comment by vtortola** [comment]
Can you link me where are you reading that? Thanks.

**Comment by willrbaar** [comment]
Link is here.  https://github.com/vtortola/WebSocketListener.  About a half page below the start of the text.
 Also, the problem I am having is disturbing.  Besides the UWP references, I also have .NETCore in the project, and when I try to get the Vtortola Websocket, NU-Get won't deliver it.

**Comment by willrbaar** [comment]
This is what I am getting back from NU-Get.---Package vtortola.WebSocketListener 2.2.2 is not compatible with uap10.0.14393 (UAP,Version=v10.0.14393) / win10-x86-aot. Package vtortola.WebSocketListener 2.2.2 supports: net45 (.NETFramework,Version=v4.5).  Not sure what this is saying, but I don't know how to get my APP to reference .NET 4.5.  Doesn't look like I'll have much chance of using Vtortola WebSocket.

**Comment by willrbaar** [comment]
This adds a little more light to the topic.  https://stackoverflow.com/questions/37778418/how-to-add-net-dll-reference-to-uwp-project   It appears that anyone playing in the UWP arena won't be able to use the .NET framework easily.  Doesn't make things impossible, but it sure makes things harder.  I don't think I'll do as they propose.

**Comment by vtortola** [comment]
I think you are looking into https://github.com/StefH/WebSocketListener instead https://github.com/vtortola/WebSocketListener . Maybe @StefH  can give you a hand with that.

**Comment by willrbaar** [comment]
I know I'm looking at Vtortola WebSockets.  I have it working on another project.  Sorry if this is wasting your time.

**Comment by StefH** [comment]
I did indeed add some more support for .NET Core in my branch. (Based on the VS2015 project.json structure).

However, we should upgrade to the new project structure from VS2017, see https://github.com/vtortola/WebSocketListener/issues/101. I will try to make a new PR for this.

I also created a NuGet which is available on https://www.myget.org/feed/Packages/websocketlistener and this one should support .NET Core.

**Comment by vtortola** [comment]
@willrbaar  not wasting my time at all, but I did not even know what UWP is, and it is not in the page of the project. Give it a try to @StefH  package. I will update to .net core 2 when it is finally released, but in the mean time I literally have no time to do it.

**Comment by willrbaar** [comment]
Val:  Sorry about being so abrupt.  I have WebSocketListner in a small prototype project, and it works well and reliably;  which I love.  My initial plans was never to get involved with Mircosoft's UWP efforts and concepts.  Unfortunately, I kept getting pushed into UWP and it has eaten up a lot of my time trying to learn new things, and fight new issues like this one.  I am very frustrated with Microsoft's grand view of where to evolve.

**Comment by ahychu84** [comment]
@StefH  I'm trying to locate the .net core compatible version of the websocketlistener but i cna't seem to find it. Could you perhaps provide a bit more clarification on how to grab this?

**Comment by StefH** [comment]
@ahychu84 Cool !

**Comment by jcahillmsft** [comment]
@vtortola: I’m not trying to be difficult, but the home page of your repo and your readme (which is what the home page of your repo is using), says in bold that this library is compatible with Universal Windows Platform which is UWP.

Here’s the link: https://github.com/vtortola/WebSocketListener/blob/master/README.md

**Comment by StefH** [comment]
Hello @jcahillmsft 

You best changes are to switch to https://github.com/deniszykov/WebSocketListener and ask your question there, maybe the author from that library can also help you?

**Comment by vtortola** [comment]
@jcahillmsft you are actually right, I did not notice that was added to the ReadMe :) (I just removed it) @StefH  is right, you may want to use @deniszykov version.
