### ISSUE TITLE
Upgrade solution to VS2017 (to add support for .NET Core and ...)

### ISSUE THREAD

**Issue by StefH** [vtortola/WebSocketListener#109]

**Comment by deniszykov** [comment]
I already did it in my #110  pull request

**Comment by willrbaar** [comment]
StefH:  My project is already in VS2017.    I tried to hook up to your MyGet  https://www.myget.org/feed/Packages/websocketlistener to get the latest version of WebSocketListner.  Not sure if I'm doing this correctly.  I'm using the NuGet Manager with package source to MyGet.  It showed a WebSocketListner 2.2.2, but I believe this is old version that is installed on my computer.  I have set up a MyGet account, but I can't seem to find WebSocketListner on MyGet to add to my feed.  It would be appreciated if you can point me in the right direction.

**Comment by willrbaar** [comment]
StefH:  I figured it out and got your WebSocketListner 3.0.0.0 into my app.  Got most of intellisense issues resolved quickly with my old code, except I need to figure out how to handle Console.ReadKey() method and other Console methods since UWP doesn't do Console.  I'll let you know if I come across any other issues with UWP.  Thanks,  this is a life saver.

**Comment by willrbaar** [comment]
StepH:  I could not get WebSocketListner 3.0.0.0 working in my UWP app.  I have the same exact code working in a prototype app with WebSocketListner 2.2.2 without issue.  The prototype is .NET 4.6.  The UWP WebSocketListner seems to communicate with the browser in the normal manner.  It goes through the handshakes with the browser to update the connection to websocket.  The browser developer tool's Network tab shows the UWP WebSocketListner actually comes back with that it upgraded.  Then in the browser's console I get the message: "WebSocket Error: Network Error 12029, A connection with the server could not be established".  I've attached a copy of my code, but it has only one minor difference between the two instantiations of WebSocketListner.  Hope this helps.  Let me know if you need anything more.
[WebSocketCode.txt](https://github.com/vtortola/WebSocketListener/files/1034490/WebSocketCode.txt)

**Comment by StefH** [comment]
If possible, upload a sample project to github?

**Comment by willrbaar** [comment]
Not sure if I know how to do that.  GitHub rejected the file when I tried to attach a .cs file, and that is why I sent the .txt file.  Would I put it on MyGet and send you the link, or can I add a zip file?  

I've inserted WebSocket, and WebSocketsRfc6455 .cs file/code directly into my project.  These are two of the things I have found and had to do to satisfy intellisense.

1) In the WebSocket/Extensions/WebSocketSecureConnectionExtension.cs, I had to add a "using System.Net.Security" to the module and then download/add a reference in the project to System.Net.Security.
2) In WebSocketHandshaker class, line 187 (handshake.Request.HttpVersion = version.EndsWith("1.1")? HttpVersion.Version11 : HttpVersion.Version10;);  the system can not find HttpVersion in System.Net.  I haven't found a way to overcome this.

These next two things are probably do to the way I am doing this and may not be applicable to the problems:

1)  You have a number of #if preprocessor statements.  My system doesn't look like they process them.  I just comment out the portions that weren't applicable to UWP, and that seemed to satisfy intellisense.
2) Tools/Guard.cs was using something called JetBrains.  Intellisense didn't like the module and I reverted to version 2.2.2 Guard module, and that made intellisense happy.

Re my above statement about WebSocketListner  handshaking with the Browser to set up the connection.  I relooked at this and I don't believe they were handshaking.  So, my error.

**Comment by willrbaar** [comment]
Repository of code created at https://github.com/willrbaar/RemoteForJRiver.  Let me know if you have any issues with it.  My first attempt at a repository.

**Comment by StefH** [comment]
I'll take a look in the next days.

**Comment by Rohansi** [comment]
Has there been any progress on this? I would like to make a project target .NET Core but this is blocking me.

There should be no need separate packages or project files (unless you need to support older VS versions).

**Comment by willrbaar** [comment]
I had success the other day.  I'm using the websocketlistner core, 3.0.0 version.  My success was do to incorporating Portable Class Library into my upw project.  Look here for pcl information, https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library.   The pcl may even allow you to use the .net version 2.5.5.  Good Luck.

**Comment by Rohansi** [comment]
.NET Standard pretty much replaces PCLs.

This should update to the [new csproj](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) and target both `net45` and a `netstandard`  framework. I'm not sure about the usefulness of a `uap10.0` target as `netstandard` should include that.
