### ISSUE TITLE
WebSocketListener not loading under mono

### ISSUE THREAD

**Issue by Muny-** [vtortola/WebSocketListener#11]
I'm developing a server which utilizes your WebSocketListener library.  It is being developed under Windows, but will need to be run and tested on linux machines under mono/wine.  The server runs fine on Windows, however when I attempt to run the application under wine or mono, I receive this error:

![Screenshot](https://pcbx.us/muny/bpqn.png)

I have all of the dependencies in the folder where the application is being run:

![Screenshot](https://pcbx.us/muny/bpql.png)

Any enlightenment on what could be causing this issue would be much appreciated.

**Comment by vtortola** [comment]
Hi, 

I see you have the Tracing dll already in place, however.. have you checked the [WebSocketListener Mono notes](https://github.com/vtortola/WebSocketListener/wiki/Mono-support])? I remember having an issue with that library and having to download the one I mention in the article.

Can you run the Mono example?

**Comment by Muny-** [comment]
No, the Mono example returns the same error.  That Tracing dll is from the download that you linked to.

Here's what mono --version returns:
```
Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-1ubuntu2.2)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            Included Boehm (with typed GC and Parallel Mark)
```

**Comment by vtortola** [comment]
Can you try to update Mono? Current version is 3.12.0, and `async` was added in 3.0, in 2012. I think you are running a old version and that is why it is not loading.

**Comment by vtortola** [comment]
Hi, I am closing this since it has no response since 20 days ago, I guess you found the issue. Otherwise please feel free to reopen the issue with further info.

Cheers.
