### ISSUE TITLE
Dual mode support: IPv4 and IPv6

### ISSUE THREAD

**Issue by drwerewolf** [vtortola/WebSocketListener#111]
Can you add dual mode support so that one WebSocketListener can support requests made via any of these protocols: IPv4 and IPv6?
This requires a small change in WebSocketListener class: use "TcpListener.Create(port)" instead of "new TcpListener(endpoint)".

**Comment by 657870** [comment]
Due the limitation of Mono TCPClient implementation you can't use one code base for this feature. Mono has no implementation for TcpListener.Create. 

If you like you can use my fork, see [IPv6 branch](https://github.com/657870/WebSocketListener/tree/IPv6) or add that feature by yourself.

**Comment by deniszykov** [comment]
You can try [my fork](https://github.com/deniszykov/WebSocketListener) which allows listen multiple endpoints or bind in dual mode if you specify host name.

[Nuget Package](https://www.nuget.org/packages/deniszykov.WebSocketListener/)
```
var options = new WebSocketListenerOptions();
options.Standards.RegisterRfc6455();
var listenEndPoints = new Uri[] {
    new Uri("ws://0.0.0.0:9998") // will listen all IPv4 interfaces
    new Uri("ws://[::1]:9997") // will listen all IPv6 interfaces
    new Uri("ws://localhost:9999") // will listen both IPv4 and IPv6
};
var server = new WebSocketListener(listenEndPoints, options);
await server.StartAsync();
```
