### ISSUE TITLE
websocket ping latency

### ISSUE THREAD

**Issue by glin-sfdc** [vtortola/WebSocketListener#113]
Hello,

I am new to this. I would like to know where I can find the code which it sends ping over websocket and measure the latency ? Also advise how to execute the code.

I would like to run this periodically , in order to monitor the websocket latency.

Please advise and thanks.

George Lin
Geo

**Comment by vtortola** [comment]
Hi. Take a look at this: https://github.com/vtortola/WebSocketListener/wiki/Measuring-WebSockets-connection-latency
