### ISSUE TITLE
Incoming message limit?

### ISSUE THREAD

**Issue by diemsi** [vtortola/WebSocketListener#119]
Hi!
How can I limit incoming message to e.g. 2kB? It would be great to not receive it completely but close websocket as soon as possible.

Thanks!

**Comment by vtortola** [comment]
Hi. You can read te message stream until you want and close the connection if the message is bigger.

I am writting this code from the top of my head, but the approach would be something like this:
```c#
var buffer = new byte[1024 * 2 + 1]; // 2kB + 1, just to check if you read more then 2kB.
var bytesRead=-1;
var totalReaded=0;
var messageReadStream = await client.ReadMessageAsync(cancellationToken);
while (bytesRead != 0)
{
   bytesRead = await messageReadStream .ReadAsync(buffer, totalReaded , buffer.Length - totalReaded);
   totalReaded += bytesRead;
}

if(totalReaded > 1024 * 2)
    throw new InvalidOperationException("Message is too large");

// to something with the first `totalReaded` bytes of `buffer`
```

**Comment by diemsi** [comment]
I've found out the same way :)
Thanks for your reply and for the awesome piece of work!

**Comment by vtortola** [comment]
Any time 👍
