### ISSUE TITLE
V3.0.0 does not work with Mono v4.6.2

### ISSUE THREAD

**Issue by hvta** [vtortola/WebSocketListener#128]
I have a Websocket chat server which works perfectly on Windows, however, when I try to make it work on a Raspberry Pi with Mono, it won't start but exit with an exception.
I get the following:

> Invalid type vtortola.WebSockets.WebSocketListenerOptions for instance field vtortola.WebSockets.WebSocketListenerConfig:<Options>k__BackingField
> 
> Unhandled Exception:
> System.TypeLoadException: Could not load type 'vtortola.WebSockets.WebSocketListenerOptions' from assembly 'vtortola.WebSockets, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
>   at WS_chat.WebSocketChat..ctor (System.Net.IPAddress ipAddress, System.Int32 port) [0x00026] in <ffa1c9d622bf401997f6a373f45453f0>:0
>   at WS_chat.Program.Main (System.String[] args) [0x00012] in <ffa1c9d622bf401997f6a373f45453f0>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'vtortola.WebSockets.WebSocketListenerOptions' from assembly 'vtortola.WebSockets, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'.
>   at WS_chat.WebSocketChat..ctor (System.Net.IPAddress ipAddress, System.Int32 port) [0x00026] in <ffa1c9d622bf401997f6a373f45453f0>:0
>   at WS_chat.Program.Main (System.String[] args) [0x00012] in <ffa1c9d622bf401997f6a373f45453f0>:0

Are you aware of this issue with the given versions and if so, do you have any solution for that?

**Comment by vtortola** [comment]
Hi, I was not aware of it. Which version of Mono are you using? https://stackoverflow.com/questions/48061333/using-net-standard-2-0-with-mono

Have you tried with 2.2.4? https://github.com/vtortola/WebSocketListener/tree/Version-2.2.4

```
PM> Install-Package vtortola.WebSocketListener -Version 2.2.4
```

**Comment by hvta** [comment]
I use Mono v4.6.2. Yes, I've tried it with v2.2.4 on Windows, but there seemed to be an error as well.

**Comment by hvta** [comment]
Now it works fine. Some dependencies were missing from our server.
