### ISSUE TITLE
IE Origin

### ISSUE THREAD

**Issue by AlhasanDeveloper** [vtortola/WebSocketListener#132]
Greetings,

I have an issue with IE where the Origin data in the httpRequest is always null, the issue is not persisted in neither firefox nor chrome.

—-
Best regards,
Abdullah

**Comment by vtortola** [comment]
Hi Abdullah,

Check this https://stackoverflow.com/questions/20784209/internet-explorer-11-does-not-add-the-origin-header-on-a-cors-request

**Comment by AlhasanDeveloper** [comment]
Thanks for the response, it turned out that the problem with the site running locally when the site was deployed to a server the HttpRequest got the origin with no problems.
