### ISSUE TITLE
Some Information about Client

### ISSUE THREAD

**Issue by Pablo-Jean** [vtortola/WebSocketListener#143]
Hello,

I'm have some doubt.
Making a solution in C#, I need to get some information about the device that connect to my server.
Using an ESP32, I know that is sent an User-Agent information, and I want to get this information to put on the screen, but I'm not finding where I get this info, can you help me?
Thanks!

**Comment by vtortola** [comment]
Hi, you can inspect HTTP headers during negotiation https://github.com/vtortola/WebSocketListener/wiki/Hooking-into-the-HTTP-negotiation
