### ISSUE TITLE
Is WebSocketListener good enough out of the box for video streaming?

### ISSUE THREAD

**Issue by nonlin** [vtortola/WebSocketListener#145]
I'd like to send data in a manner that the most recent up-to-date frame gets through.
It seems like there is no way to apply backpressure. When my messages arrive faster than the server can handle them, the reading method seems be buffering in the old messages. I can slow down the rate at which my client sends them and then it seems to keep up but this is not a valid solution for attempting to stream bytes of data which is a video frame.  

I thought websocket is more of a stream? But I'm new to this and starting off with a non-trivial task so my understanding might be off.

**Comment by deniszykov** [comment]
If you want out of order framing, this is not achievable with TCP/WebSockets.
For backpressure you could stop/pause reading data from socket and it will exaust receive window of socket and prevent from receiving new frames.

**Comment by nonlin** [comment]
I got video streaming to work and I'd say it is good enough. 
I do not need out of order framing so that may not have been clear.
