### ISSUE TITLE
Websocket Listener is able to accept incoming data from Client but Websocket Listener thinks connection with client is closed.

### ISSUE THREAD

**Issue by nonlin** [vtortola/WebSocketListener#146]
In my case an Android device is establishing a connection via this WebsocketListener on a windows machine but when the Android device goes to sleep and wakes up, it is able to still send data to the Listener but the Listener says websocket connection closed when it tries to send data back to Android device. 

I guess the heartbeat to keep the connection alive is terminated but what can be done to re-established the same connection again from the Listener to client automatically once android device wakes up?

**Comment by deniszykov** [comment]
> but the Listener says websocket connection close

Ping timeout setting probably. 2 skipped pings = terminated connection.

> I guess the heartbeat to keep the connection alive is terminated but what can be done to re-established the same connection again from the Listener to client automatically once android device wakes up?


When TCP connection is terminated, then no way back. Just re-connect.
