### ISSUE TITLE
IIS8 dll

### ISSUE THREAD

**Issue by Konstantin5** [vtortola/WebSocketListener#15]
sorry it's not an issue but a question: can WebSocketListener be used as a 'bridge' between IIS8 and a Delphi .dll, which works as a module in IIS8. This .dll serves dynamic pages, using these functions: GetExtensionVersion HttpExtensionProc TerminateExtension. Can that dll access websockets, to run both types of traffic on the same port 80?

**Comment by vtortola** [comment]
I am afraid I have no idea about that Delphi dll, but if you find out please share :)

**Comment by vtortola** [comment]
The http.sys built in Windows 8/2012 and further is the one that enables that switch that allows to share the same TCP port. Honestly, I doubt that any IIS8 module can get the raw TCP stream from IIS8.

**Comment by Konstantin5** [comment]
even if not on the same :80 port? MSDN has few examples with ASP.NET (http://blogs.msdn.com/b/youssefm/archive/2012/07/17/building-real-time-web-apps-with-asp-net-webapi-and-websockets.aspx).. I'm not that great on this stuff, but it must be some linkage to those 'HttpExtensionProc' functions, exposed by IIS8 - not?

**Comment by vtortola** [comment]
That API that appears on that link, is the Windows native WebSocket API, it does what WebSocketListener does but integrated with IIS8, so basically it gives you WebSocket objects. I doubt it is possible to be honest.

**Comment by Konstantin5** [comment]
so WebSocketListener can't be integrated with IIS8 ? (sorry for basic questions)

**Comment by Konstantin5** [comment]
"Since the initial upgrade handshake for WebSockets looks just like an HTTP request/response" we should get it in 'HttpExtensionProc' function. Problem is what to do with it further.. will investigate.

**Comment by vtortola** [comment]
Right, it cannot integrate with IIS8.
