### ISSUE TITLE
Question about peformance when accepting clients

### ISSUE THREAD

**Issue by StefH** [vtortola/WebSocketListener#17]
I did some small tests by using a client based on the chat client from https://www.websocket.org/ and I created a c# test client based on https://github.com/sta/websocket-sharp#websocket-client

When running the WebSocket server based on your chat example, it seems that the server can connect about 50 WebSocket connections per second.

Is this a limitation on your code / my system or do I need to tweak the WebSocketListenerOptions ?
Please advice.

**Comment by vtortola** [comment]
Yes, there were a limitation in the TransformBlock<> that was enforcing order. It has been removed as explained in this issue: https://github.com/vtortola/WebSocketListener/issues/14

Not yet in the NuGet package, but you can get the latest source code or the assemblies from: https://ci.appveyor.com/project/vtortola/websocketlistener/build/artifacts

If you could try with the latest code and check if the connections per second have improved in your test I will be very grateful :)

Cheers.

**Comment by StefH** [comment]
I'll try to retest using the latest code and I'll post some results.

**Comment by vtortola** [comment]
So it is the same. I will put this as first time in my TODO list.Still it is not bad considering that WS are supposed to be persistent. Is this being a problem for your project currently?

**Comment by StefH** [comment]
Building up connections is one thing, maintaining and sending data for a lot of clients is also another functionality.
Do you know maybe how many websocket clients can connect to a single server? Is that limited to mem or cpu ?

**Comment by vtortola** [comment]
I run my own performance tests: https://github.com/vtortola/WebSocketListener/wiki/WebSocketListener-performance-tests

It is limited to CPU, memory, message length and bandwidth. I managed to set up 4000 clients and each client was still able to send 11 messages of 1K each in each direction.

**Comment by StefH** [comment]
Nice performance article, I'll have a detailed look at that.

About a WebSocket client running on Windows 7 : I'm using another implementation, see this sample project : https://github.com/StefH/WebSocketTest/tree/master/WebSocketTestSolution/WebSocketClient

Maybe it's also a good idea to add some performance test tools to this github ?

**Comment by vtortola** [comment]
I prefer to have the performance tools in separate repositories.

**Comment by StefH** [comment]
OK, the test tools are located in : https://github.com/vtortola/WebSocketEchoLoadGenerator ?

**Comment by vtortola** [comment]
Right. That is the tool I use to test performance.
