### ISSUE TITLE
NuGet version 2.1.5.0 has dependency on System.Threading.Tasks.Dataflow, Version=4.5.9.0 which is not correct?

### ISSUE THREAD

**Issue by StefH** [vtortola/WebSocketListener#18]
I'm using '2.1.5.0' from NuGet.

When starting an example, I get this error message:

Error	2	Assembly 'vtortola.WebSockets, Version=2.1.5.0, Culture=neutral, PublicKeyToken=null' uses 'System.Threading.Tasks.Dataflow, Version=4.5.14.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Threading.Tasks.Dataflow, Version=4.5.9.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	d:\Github\WebSocketTest\WebSocketTestSolution\packages\vtortola.WebSocketListener.2.1.5.0\lib\net45\vtortola.WebSockets.dll	WebSocketTest

I can only solve this by upgrading TPL to version 4.5.14 and also updating my app.config file.

**Comment by vtortola** [comment]
Are you using Mono by chance?

https://github.com/vtortola/WebSocketListener/wiki/Mono-support

**Comment by vtortola** [comment]
I will take a look

**Comment by vtortola** [comment]
You are right, the NuGet configuration has one version, but the assembly requires other. I will fix this tomorrow releasing a new NuGet package.

Thanks for taking time to report this :+1:

**Comment by StefH** [comment]
Latest most recent version is 4.5.24

**Comment by vtortola** [comment]
Released a NuGet package 2.1.7 that has updated references: http://www.nuget.org/packages/vtortola.WebSocketListener/

**Comment by StefH** [comment]
Thanks
