### ISSUE TITLE
CLS compliance ?

### ISSUE THREAD

**Issue by ramlongcat** [vtortola/WebSocketListener#21]
Hi, i'd like to use your nugget but it is not CLS compliant.
Any idea if that's something you can fix ?

**Comment by vtortola** [comment]
I can try to make it CLS compilant if it is not much hassle. The problem is all the unsigned integers being used. I can take a look and see.

What language are you using?

**Comment by vtortola** [comment]
Try with these assemblies and let me know if it works for you:

https://ci.appveyor.com/project/vtortola/websocketlistener/build/artifacts

**Comment by ramlongcat** [comment]
Yep -- these assemblies seem to be CLS compliant.
Although I'm using Nugget to reference your library... do you plan to update your nugget with those changes any time soon ?
Thanks for your help !

**Comment by vtortola** [comment]
No problem :+1: 

It will get into NuGet next time I do a release. I want to include other changes but I am a little bit busy at the moment, so I cannot guarantee it will happen before two weeks :(

I will post a message here when I do it.

**Comment by ramlongcat** [comment]
awesome.
thanks for your help!

**Comment by vtortola** [comment]
It took long enough...

I have included it in version 2.1.8 that you can find in NuGet.
