### ISSUE TITLE
how to send binary data over websocket?

### ISSUE THREAD

**Issue by trivedi1980** [vtortola/WebSocketListener#25]
Please share some sample code on sending binary data to clients using this library?

**Comment by vtortola** [comment]
It is in the main page, in the "Sending messages" section:

```csharp
using (var messageWriter = ws.CreateMessageWriter(WebSocketMessageType.Binary))
   await myFileStream.CopyToAsync(messageWriter);
```

Cheers.

**Comment by trivedi1980** [comment]
Thanks for the quick response. I am having another question regarding deflate compression support for Safari browser. When I tested with sample web socket app on Safar, it is sending extension as x-webkit-deflate-frame and found that WS HTTP handshake response doesn't have ws-extension header. Wondering if this is supported in safari browser or not?

**Comment by vtortola** [comment]
The browser should issue a request containing something like: 

```
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits, x-webkit-deflate-frame
```
As far as I remember `x-webkit-deflate-frame` was the experimental support, but `permessage-deflate` **will be** the standard (I believe it is still a draft).

The server should reply a response with:
```
Sec-WebSocket-Extensions: permessage-deflate
```
Indicating that the extension is accepted, otherwise, check this howto to see if you configured it right: https://github.com/vtortola/WebSocketListener/wiki/Deflate-extension

**Comment by trivedi1980** [comment]
I did registered deflate extension as per the documentation and for Chrome it is getting response with "Sec-WebSocket-Extensions: permessage-deflate; " but thats not happening with Safari browser. The only difference is Chrome sends "permessage-deflate" in request whereas Safari sends "x-webkit-deflate-frame".

**Comment by vtortola** [comment]
In that case it won't work.

You can try to reuse my code to create your own, for example if the semantics are exactly the same you can try something like:

```csharp
public sealed class WebSocketSafariDeflateExtension : IWebSocketMessageExtension
{
    public string Name { get { return "x-webkit-deflate-frame"; } }

    static readonly WebSocketExtension _response = new WebSocketExtension("x-webkit-deflate-frame", new List<WebSocketExtensionOption>(new[] { new WebSocketExtensionOption() { Name = "client_no_context_takeover" } }));
    public bool TryNegotiate(WebSocketHttpRequest request, out WebSocketExtension extensionResponse, out IWebSocketMessageExtensionContext context)
    {
        extensionResponse = _response;
        context = new WebSocketDeflateContext();
        return true;
    }
}
```

Again this is assuming that "client_no_context_takeover" works also when using "x-webkit-deflate-frame".

**Comment by trivedi1980** [comment]
i have followed this approach, but initial handshake is failing for safari browser. I can see that the extension is getting invoked during handshake, but client throws error saying invalid header "deflate-frame"

**Comment by trivedi1980** [comment]
Here is the actual error on browser console for Safari:

WebSocket connection to 'ws://3.20.165.63:28818' failed: Received unexpected deflate-frame parameter

**Comment by vtortola** [comment]
That is probably because Safari's implementation does not support the parameter "client_no_context_takeover", which is needed to work with `DeflateStream` compressing message by message. Sorry.
