### ISSUE TITLE
how to read binary messages

### ISSUE THREAD

**Issue by philkoh** [vtortola/WebSocketListener#33]
The example snippet on your main github page uses an object called "messageReader" - where does this come from?  I can't understand how to get messageReader from messageReadStream, thanks.

if(messageReadStream.MessageType == WebSocketMessageType.Binary)
{
   using (var ms = new MemoryStream())
   {
       await messageReader.CopyToAsync(ms);
   }
}

**Comment by vtortola** [comment]
That is a typo :) It should be:

```
if(messageReadStream.MessageType == WebSocketMessageType.Binary)
{
   using (var ms = new MemoryStream())
   {
       await messageReadStream.CopyToAsync(ms);
   }
}
```

**Comment by philkoh** [comment]
Thanks.  When I try that code and send a five-byte binary test message to the listener, even after executing CopyToAsync,the object  'ms' has a length of zero, so I am unable to receive the binary message.

**Comment by philkoh** [comment]
Sorry, ignore previous comment.  Length is now non-zero.   Working on converting it to a byte array.

**Comment by philkoh** [comment]
I did see some odd behavior.  Every time I sent a five-byte message (using WebSocket4Net), it was always received, and the MessageType was always correctly shown as binary.  Most of the time, stream ms had a length of 5, but every so often it emerged with a length of zero.
   The misbehavior was hard to replicate.  It seemed perhaps timing-dependent.  Running at full speed seemed to work consistently.  When I stepped through the code using the debugger, this occasionally resulted in a zero-length ms stream.   I am a newbie at websockets so I can't rule out that this is a problem on my end.  My VB code below.  With every test message it always reached the last line, but sometimes at the end bbbb had length zero and sometimes length 5.
  
      Async Sub WaitForMessage(clientbrowser As vtortola.WebSockets.WebSocket)
        Dim cancellationToken = Nothing
        Dim messageReadStream As vtortola.WebSockets.WebSocketMessageReadStream = Await clientbrowser.ReadMessageAsync(cancellationToken)
          Select Case messageReadStream.MessageType
            Case vtortola.WebSockets.WebSocketMessageType.Binary
            
                Using ms As System.IO.MemoryStream = New System.IO.MemoryStream

                    Await messageReadStream.CopyToAsync(ms)
                    ms.Position = 0
                    Dim bbbb(ms.Length - 1) As Byte
                    ms.Read(bbbb, 0, ms.Length)

**Comment by vtortola** [comment]
That is very strange. I have been trying to do something like that and I always get the 5 bytes. Try to pinpoint a reproducible case and I will take a look.
