### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by LennyPenny** [vtortola/WebSocketListener#34]
Would be awesome if you could compile the nuget package for the coreclr framework. 
Can I do that myself somehow for now?

**Comment by vtortola** [comment]
Yes, give it a try and we can see how difficult would be. There are some dependencies on other assemblies, so I not completely sure it would work out of the box.

**Comment by LennyPenny** [comment]
I unfortunately have no idea how to compile c# packages myself and installing them. Any idea where I could read that up?

**Comment by vtortola** [comment]
Neither do i :D

**Comment by papci** [comment]
hey,

dnx support will be definitely great ! I can do it, but it will require large modifications (including in the sln structure).
Here's the main approach :
- changing every csproj to xproj (with just dnx451 support)
- checking that the classic dotnet platform support is not broken
- adding dnxcore 5.0 support

Tell me what you think

**Comment by vtortola** [comment]
Would that somehow break compatibility with VS2013 and .NET 4.5.1 ?

**Comment by papci** [comment]
I don't know if VS2013 support xproj project. But it will no break .net 4.5.1 support.

**Comment by vtortola** [comment]
I am going to be incredibly busy until Xmas. I can create a new branch and we can experiment there, however if you need my support I cannot guarantee that will happen straight away :(

Would that suit you?

**Comment by papci** [comment]
An experimental branch would be nice ;) 
Thanks !

**Comment by papci** [comment]
I have good news. I tried to implement dotnet core support, and it went well.
you can check it on my forked repo. (here : https://github.com/papci/WebSocketListener).

If you want to check if it's compatible with VS2013, feel free to do it  :)

Thanks.

**Comment by StefH** [comment]
I've forked from papci and added support for more frameworks: 
* net45, net451 and net452
* dnx451 and dnx451
* dnxcore5

And i was able to compile dnxcore5 on Linux, however the UnitTest project cannot compile/run because Moq is not present for dnxcore5. (Maybe also nunitlite has some issues.)

**Comment by vtortola** [comment]
I still have to take a look to the changes that @papci did (sorry, i had busy Xmas :( ) 

@StefH do you have the code somewhere?

**Comment by StefH** [comment]
Code is present in my branch (which was forked from papci)

https://github.com/StefH/WebSocketListener

**Comment by vtortola** [comment]
Sorry I have been trying to find free time to take a look at this and due some personal committments I just can't :( I see you guys are doing progress. I will try to follow up and in the meantime please reach me for any question you may have about the standard code. Thanks!

**Comment by StefH** [comment]
dotnet rc2 support --> netstandard 1.3
See pull request:
https://github.com/vtortola/WebSocketListener/pull/65

**Comment by Supergeek** [comment]
Considering the difficulty of importing DLLs into Core, it would be greatly appreciated if someone would publish one of their Core-compatible forks to Nuget.

**Comment by vtortola** [comment]
Hi, I think @StefH already did some work on this https://www.nuget.org/packages/vtortola.WebSocketListener.dnx/2.2.0.1-beta-00002

**Comment by StefH** [comment]
This is some time ago. I'll see if I can find some time to check my project and upgrade if needed. And also check that NuGet package.

**Comment by StefH** [comment]
I've updated the project again to latest netstandard.

Initial NuGets are created and pushed to myget.org : https://www.myget.org/F/websocketlistener/api/v3/index.json

Please try.

I'll create a PR later (I've tried to keep the changes/differences minimal, but I'll have some discussions with @vtortola on that I guess...)

**Comment by deandob** [comment]
Hi, do post when these dotnet core changes are merged back in the main branch and available. Thanks for the time spent on this.

**Comment by StefH** [comment]
Code is merged to main. However some work is needed. See also https://github.com/vtortola/WebSocketListener/pull/93

**Comment by vtortola** [comment]
Done un 3.0.0
