### ISSUE TITLE
issue with PingTimeout setting

### ISSUE THREAD

**Issue by trivedi1980** [vtortola/WebSocketListener#37]
Hi ,

On latest code, I observed that the listener is NOT considering the PingTimeout value setting (for ex: 120 seconds) and it is always sending ping requests every 0.5 seconds. I found that the ping interval was wrongly calculated in LatencyControlPing.cs by using min value between 0.5 and half of PingTimeout value. My understanding is that we should take "max" value instead of "min", please correct me if that is not right?

Thanks,
Trivedi

**Comment by vtortola** [comment]
I think you are right, and it is actually also wrong in BandwidthSavingPing.cs. It is a guard condition to ensure nobody puts a ridiculously short ping interval.

Thanks for taking the time in reporting this :+1:

**Comment by vtortola** [comment]
Committed in https://github.com/vtortola/WebSocketListener/commit/f40c1aab7feca9e8ed7f3c2e3af72a38b7912270

I am very busy these days, but I will try to put more testing into this.

**Comment by trivedi1980** [comment]
thank you and appreciate your time for putting the fix.
