### ISSUE TITLE
PingTimeout event

### ISSUE THREAD

**Issue by michaeled** [vtortola/WebSocketListener#38]
Is there a builtin method to determine if a user was disconnected through a ping timeout? Should i keep a  list of open sockets and query them periodically to see if they're open?

**Comment by vtortola** [comment]
Check this code snippet : https://github.com/vtortola/WebSocketListener/wiki/WebSocketListener-Echo-Server-Example#user-content-processing-input

Basically when the `while` loop ends, it is a good moment to check the `IsConnected` property and figure out if it is connected or not. Disconnection may happen by many things, including trying to write a `ping` to the socket and get an error.

However there is no hook or event to get notified when this happen.
