### ISSUE TITLE
Localhost and Microsoft Edge 

### ISSUE THREAD

**Issue by MrBean2016** [vtortola/WebSocketListener#43]
I am investigation a solution where a native software needs to communicate with a webapp on localhost. I have built the very simple Echo-sample and it works in Chrome and IE 11 but not in Microsoft Edge 25.10586.0.0. I have checked in about:flags that localhost is allowed.

The same javascript is used in all Browser. In Edge, the Onclose event returns 1006 "The connection was closed abnormally, e.g., without sending or receiving a Close control frame" after a couple of seconds.

Do I need to do something to get this working on Edge or is it time to face the reality that it not possible to use websockets on localhosts? 

Thanks,

The script used for testing

              var ws = new WebSocket("ws://localhost:8005");

               ws.onopen = function()
               {
                  // Web Socket is connected, send data using send()
                  ws.send("Message to send");
                  alert("Message is sent...");
               };

               ws.onmessage = function (evt)
               {
                  var received_msg = evt.data;
                  alert("Message is received...");
               };

               ws.onclose = function(event)
               {
                   // websocket is closed.                   
                       var reason;
                       alert(event.code);
             }

**Comment by vtortola** [comment]
Almost 2016 and still debugging Microsoft's browser incompatibilities... I guess some things never change :)

Have you tried to connect to `ws://127.0.0.1:8005` ?

I don't have and Edge at hand at the moment, but I will give it a look later.

**Comment by MrBean2016** [comment]
I have investigated a bit further. In Win 8 and Windows 10 all modern apps runs in AppContainers that are forbidden to send network traffic to the local Computer. Edge is regarded as a modern app. 
There are some developer tools to fix this on developer computers http://loopback.codeplex.com/

Also described here
https://blogs.windows.com/msedgedev/2015/05/11/microsoft-edge-building-a-safer-browser/
"Microsoft Edge is rebooting our browser extension model, allowing it to run its content processes in app containers, not just as a default, but all the time. Thus every Internet page that Microsoft Edge visits will be rendered inside an app container, the latest and most secure client-side app sandbox in Windows."

**Comment by vtortola** [comment]
Fantastic, as usual they are helping us by breaking our apps :)

Thanks for the info.
