### ISSUE TITLE
Trying to call from node.js socket.io-client

### ISSUE THREAD

**Issue by deejbee** [vtortola/WebSocketListener#44]
I'm struggling to get anywhere with with this so far.  I'm just running up the echo sample code as a console app and I want a node.js app on the same machine to call functions in it (echo for now).

When I use socket.io-client with something like io.emit('hello')  I don't see anything in the console app.

I see AcceptWebSocketClientsAsync being fired intermittently when the console app is running but that's it.  The HandleConnecionAsync never fires.

Any pointers what I'm doing wrong?
Thx.

**Comment by vtortola** [comment]
As far as I know, socket.io is more than just a WebSocket client, like SignalR. So I don't think you can connect to a WebSocket server straight away with it.Probably it will try to connect and do some kind of negotiation. Can you for example connect to wss://echo.websocket.org and get responses?

Cheers.
