### ISSUE TITLE
HTTP Server with websockets

### ISSUE THREAD

**Issue by Slyb00ts** [vtortola/WebSocketListener#45]
Hi,

first id like to congrats you for this code;) at least someone is using async as it should :)
But id like to ask you if you have a way to provide simple http server also? I need to provide some files over http/https including js, so then it will connect using websockets. Im using at the moment websocketsharp, its nice, but its not async, and its blocking whole server, when someone got slower connection and send larger messages. I wasnt playing with your code yet much, so im asking without checking it.
If there is http/https now, maybe there is a way to make a plugin?

Regards,
Piotr

**Comment by vtortola** [comment]
Thanks!

I am afraid that serving files via HTTP is out of the scope of this component. Why would you need such thing? Remember that WebSockets are not constrained by the browser's Same Origin Policy, so the web page can be in one host and still connect to other. Also, they can run in different ports, so probably there is other project you can use to setup a self-hosted HTTP server in the same host.

Cheers.

**Comment by xljiulang** [comment]
@Slyb00ts 
hi Slyb00ts ,this may be what you need: 
https://github.com/xljiulang/NetworkSocket

**Comment by Slyb00ts** [comment]
I know there are other projects, but the thing is i want to run it on 1 port instead of 2. I have this now with websocketsharp, but as i said earlier weboscketsharp got some issues with blocking...

**Comment by pboyer** [comment]
If you're using linux, I know you can use HAProxy to host them on the same
port.

I agree w @vtortola - keep it simple.
