### ISSUE TITLE
Client with event mode in c#?

### ISSUE THREAD

**Issue by AshIceLoky** [vtortola/WebSocketListener#46]
Hi,
I try your API for high frequency system (up to 1000 messages/second with 10 clients).
I try PowerWebSocket, a commercial API and your API. What client for a WPF application is the best (I use your EVENT based server)?
thanks

**Comment by vtortola** [comment]
Hi,

Bear in mind that the event based wrapper is just a prototype and almost nobody uses it (including me), I recommend you to go "async/await" all the way if you are really concerned about scalability and performance. Somebody was reporting a connection issue some time ago and I suspect it was for the way threads were used with the event wrapper : https://github.com/vtortola/WebSocketListener/issues/39

I use the built in `ClientWebSocket` from .NET. I have tried other clients and I always ran into issues. You can also create an event wrapper, still I encourage you to go with the async/await model.

Cheers.
