### ISSUE TITLE
question: How to restrict to URI

### ISSUE THREAD

**Issue by agimenezwally** [vtortola/WebSocketListener#51]
Hi.

I'm using the server and it works very well.
Only I wanted to know if there is any way to register the listening URL and only answer to the registered URI.

Actually I'm using the OnHttpNegotiation and throwing an exception, but this results in a 503 internal server error (I see it's programmed this way) and I will like to return a 404 with a personalized message.

Is this possible?

Thanks.

**Comment by vtortola** [comment]
Hi,

Yes you can, take a look to [Hooking into the HTTP negotiation](https://github.com/vtortola/WebSocketListener/wiki/Hooking-into-the-HTTP-negotiation):

```cs
new WebSocketListenerOptions() 
{ 
    OnHttpNegotiation = (request, response)=>
    {
            response.Status = HttpStatusCode.Unauthorized;
    }
}
``` 

However there is no way to put a custom status description. Where do you see the HTTP 503? Are you sure is not HTTP 500? I don't recall any 503 in the source code.

Cheers.

**Comment by agimenezwally** [comment]
Thanks for the answer, I think I can live with just a 404 with no message, a lot better than an exception :+1: 

About the 503, well, I saw it on the browser and I supposed the InternalException had that code, but today has been a long day and I may have confused the error pages.

Thanks again.
