### ISSUE TITLE
 Unhandled exception occurred during GC.Collect()

### ISSUE THREAD

**Issue by jacobs100500** [vtortola/WebSocketListener#56]
In my logs i found this record:
`Unhandled Exception:`
`System.NullReferenceException: Object reference not set to an instance of an object`
`at vtortola.WebSockets.Rfc6455.WebSocketRfc6455.Dispose (Boolean disposing) <0x41364c50 + 0x00042> in <filename unknown>:0`
`at vtortola.WebSockets.Rfc6455.WebSocketRfc6455.Finalize () <0x413cac60 + 0x0001d> in <filename unknown>:0`

I tried to restore the situation in which it happened, and that's what came out of it.
if the class (WebSocketRfc6455) constructor, an exception is thrown, and then turn on GC.Collect(), function Dispose(bool) call Connection.Dispose(). But property Connection is null, because in the class constructor, an exception is thrown and Connection not set.

**Comment by vtortola** [comment]
Thanks for taking time in reporting this. I will take a look :+1:

**Comment by vtortola** [comment]
I will include a fix for this next week together with other small changes.

**Comment by vtortola** [comment]
Did you by chance catch the actual exception that is thrown at the constructor? (not the one that was caught by the GC).

**Comment by jacobs100500** [comment]
An exception in the constructor is caught ok. This my code for test:
```
public WebSocketRfc6455(Stream clientStream ... ) :base(httpRequest, httpResponse)
{
    throw new Exception("Test");

    if (clientStream == null)
        throw new ArgumentNullException("clientStream");
    ...
}
```
After starting WebSocketListener, called GC.
```
WebSocketListener listner = new WebSocketListener(endPoint, options);
...
listner.Start();

Console.ReadKey();
GC.Collect();
```
When a client connects, the "Test" exception is thrown, and the connection is closing (closing clientStream, but class WebSocketRfc6455 not dispose). Then i press Enter and triggered GC. GC tries to dispose class WebSocketRfc6455, and throwns the exception `System.NullReferenceException: Object reference not set to an instance of an object`

**Comment by vtortola** [comment]
What I mean is if you caught the original exception that was thrown in the constructor when you discovered this issue first? I am interested in knowing what failed in the constructor that time.

**Comment by jacobs100500** [comment]
Unfortunately, I do not know what happened at that time. The logs record only preserved this exception.

**Comment by vtortola** [comment]
I believe it has been fixed in: https://github.com/vtortola/WebSocketListener/commit/cae9c5e119ce2fc9c8aca3e96d8a34eead856a3d

If you have the chance to get latest source and try it would be great :)

Cheers.

**Comment by jacobs100500** [comment]
I upgrade my source. Error is not occurred :) But I will still keep an eye.

I have long since found the problem, but I do not know this is a problem in the code or incorrect data.

First. Thrown the exception "Cannot parse cookie string". Cookie data: _ym_isad=2; __test; settings=...
because: The 'Name'='__test; settings' part of the cookie is invalid.

Second. In some websocket frames lacks one byte. I don't have a raw data now. If necessary, i will get later.

**Comment by vtortola** [comment]
Sent frames always lack one byte, the final one, that is sent when you close the stream.

Do you have the complete cookie data? That one is interesting.

**Comment by jacobs100500** [comment]
It's problem with incoming frames. For example, server receives json data without last symbol "}".

Full exception message: 
Cannot parse cookie string: 'language=ru; _ym_uid=1459682501809792379; _ym_isad=2; __test; settings=%7B%22market_730_onPage%22%3A24%7D; timezoneOffset=10800' because: The 'Name'='__test; settings' part of the cookie is invalid.

These are not my cookies. I don't remember what browser, but is real device (not bot). Also I can keep track of this information.

**Comment by jacobs100500** [comment]
It's problem with incoming frames. For example, server receives json data without last symbol "}".

Full exception message: 
Cannot parse cookie string: 'language=ru; _ym_uid=1459682501809792379; _ym_isad=2; __test; settings=%7B%22market_730_onPage%22%3A24%7D; timezoneOffset=10800' because: The 'Name'='__test; settings' part of the cookie is invalid.

These are not my cookies. I don't remember what browser, but is real device (not bot). Also I can keep track of this information.

**Comment by vtortola** [comment]
Fixed the cookie thing: https://github.com/vtortola/WebSocketListener/commit/616f2578e4156cb1905e2f69cddb2a751baf2a46

I am going to review my latest changes to see if I cannot spot that problem you say about missing frames. If you come across a reproducible case let me know.

**Comment by vtortola** [comment]
I have been running a small stress test that creates random JSON objects with random numbers of properties and random values against an echo service with WebSocketListener, and I always get echoed the right object, with both ws:// and wss://

https://gist.github.com/vtortola/eead57d64bf4645c7e91176e2977d920

I think `ClientWebSocket` does not use compression, but the tests I have made with the browser always run fine. Keep an eye on it, I would be very interested in finding out what could go wrong, but also review your own code you may have something fishy.

Cheers.

**Comment by jacobs100500** [comment]
I found an old log with a description of the error. 

Message 1 (Pong frame):
Bytes: 8A814FBBE841
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

Message 2 (Text frame):
Bytes: 81E935146C9C052517BE466009FD584B05F8172E5BAA00225DAD0C2C5DAE00265DA800265CB0176005F1503656AD01215FAE07215CAB07384EF4546704BE0F363EED637830B3425C04F1547E3FD353401ED0634E0FDD7B5236F7637D2BCA047A58C4504636C9477129AE567B51BE
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

This client had a browser Google Chrome of the latest version (the latest version on January 2016)
