### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by 657870** [vtortola/WebSocketListener#63]
Can we get an updated NuGet package or do you perfom a cyclic release model?

**Comment by vtortola** [comment]
Not really. As long it is not a major issue, I wait to have a bunch of corrections before releasing. I will release a new package today.

**Comment by vtortola** [comment]
Hi,

I published it: https://www.nuget.org/packages/vtortola.WebSocketListener/2.2.0.2

Cheers.

**Comment by 657870** [comment]
Thanks. Issue can be closed.
