### ISSUE TITLE
Method 'TcpListener.Create' not found. Mono 4.4.0

### ISSUE THREAD

**Issue by atonamy** [vtortola/WebSocketListener#66]
On latest mono version (Mono 4.4.0) this library doesn't work.

`WebSocketListener server = new WebSocketListener(endpoint);`
this code throw exception 
**Method 'TcpListener.Create' not found.**
I found description of this bug here https://bugzilla.xamarin.com/show_bug.cgi?id=38167
Can you fix it?

**Comment by vtortola** [comment]
Sure, I will fix it tonight. I guess there is no way to have dual sockets and still make it work in both windows and Mono.

**Comment by vtortola** [comment]
Fixed.
