### ISSUE TITLE
WebSocketMessageReadNetworkStream Error only in mono

### ISSUE THREAD

**Issue by Cstansf** [vtortola/WebSocketListener#69]
Using .Net I can Send message from System.Net.WebSockets.ClientWebSocket but using Mono (same code) I receive an error -> WebSocketMessageReadNetworkStream can only start with a Text or Binary frame, not Continuation. Thanks

**Comment by vtortola** [comment]
Hi,

Can you show me how are you setting up the listener? Are you using compression?

Cheers.

**Comment by Cstansf** [comment]
Hi val using it straight from mono sample…


            var endpoint = new IPEndPoint(IPAddress.Any, 3333);
            WebSocketListener server = new WebSocketListener(endpoint, new WebSocketListenerOptions() { SubProtocols = new[] { "text" } });
            var rfc6455 = new vtortola.WebSockets.Rfc6455.WebSocketFactoryRfc6455(server);
            server.Standards.RegisterStandard(rfc6455);
            server.Start();

Thanks

**Comment by Cstansf** [comment]
Val,

I figured it out. Was my bad all along. I had wrong version of mono and Client was choking. I am sorry for wasting your time.

Thanks

**Comment by vtortola** [comment]
No problem at all. I'm happy it was sorted out :+1:
