### ISSUE TITLE
Secure connection issue

### ISSUE THREAD

**Issue by ahychu84** [vtortola/WebSocketListener#71]
Here is a snippet of the code I am using to start the server. I'm running this in mono.

```C#
X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
store.Open(OpenFlags.ReadOnly);          
var cert = store.Certificates[0];
store.Close();            

var options = new WebSocketListenerOptions()
{
    NegotiationQueueCapacity = 128,
    ParallelNegotiations = 16
};
            
WebSocketListener secureServer = new WebSocketListener(
    new IPEndPoint(IPAddress.Any,Convert.ToInt32(ConfigurationManager.AppSettings["wss_port"])),     
    options);

secureServer.Standards.RegisterStandard(new vtortola.WebSockets.Rfc6455.WebSocketFactoryRfc6455(secureServer));
secureServer.ConnectionExtensions.RegisterExtension(new WebSocketSecureConnectionExtension(cert));
secureServer.Start();
```

In my html file i'm simply doing a 
```javascript
var ws = new WebSocket("wss://hostname:wss_port");
```
Am i missing anything? In the console, I'm seeing a Error in connection establishment: net::ERR_CONNECTION_CLOSED. I've tried in several different browsers and all exhibit the same error. I am using a cert bought from geostore and it is the only cert installed in my store.

Any help would be much appreciated.

**Comment by vtortola** [comment]
Is the connection using HTTPS as well with the same certificate?

**Comment by ahychu84** [comment]
Yes it is

**Comment by vtortola** [comment]
Have you tried in another port?

**Comment by ahychu84** [comment]
yep have tried 3

**Comment by vtortola** [comment]
if you remove the `WebSocketSecureConnectionExtension` it works fine?

**Comment by ahychu84** [comment]
Yep I have two ports open. one which listens to regular Web socket calls and the other one is for secure connections. The regular port has been working since day 1. Now just struggling to implement the secure port. 


Sent from my Samsung Galaxy smartphone.<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Val <notifications@github.com> </div><div>Date: 6/14/16  1:31 PM  (GMT-07:00) </div><div>To: vtortola/WebSocketListener <WebSocketListener@noreply.github.com> </div><div>Cc: ahychu84 <adam.chu@shaw.ca>, Author <author@noreply.github.com> </div><div>Subject: Re: [vtortola/WebSocketListener] Secure connection issue (#71) </div><div>
</div>if you remove the `WebSocketSecureConnectionExtension` it works fine?

---

**Comment by AndyM84** [comment]
Would like to confirm this is an issue.  Have no issues using the system without a secure connection, but as we have switched our website over to using HTTPS we must use WSS in order to connect.  Have used the same cert as the website as well as a new cert with a different domain, always unable to connect over WSS.

**Comment by vtortola** [comment]
Have you tried to make it work with a self-signed certificate first?

There is not much I can help, as you can see the WSS:// supports is just a [very simple implementation with `SslStream`](//github.com/vtortola/WebSocketListener/blob/master/vtortola.WebSockets/Extensibility/WebSocketSecureConnectionExtension.cs).

I have tried with a self-signed certificate (I do not have other to try) and it works. Anyway if you find the problem to be in the implementation code let me know and I will fix it.

**Comment by AndyM84** [comment]
Just tried again with a self-signed certificate, same result.  I can confirm in all instances that the same issue happens in both Firefox and Chrome (didn't get around to checking others as it wouldn't matter if those two don't work).  Will try and find some time to test using a manual build instead of pulling from NuGet.  What did you use to build your self-signed certificate?

**Comment by vtortola** [comment]
I used IIS to create one with pretty much the default options. I use Chrome and it works using Windows, but this maybe a Mono thing (I don't mean Mono is broken, but maybe something the code is doing should be different). Unfortunately I do not have a machine with Linux anymore :( 

As a test, I would tell you to create a simple SSL server and client in Mono and try to use that certificate and see if it works.

Take also a look to this SO question: http://stackoverflow.com/questions/18462064/associate-a-private-key-with-the-x509certificate2-class-in-net/24863777

**Comment by AndyM84** [comment]
Was able to modify our approach using the following information:

http://stackoverflow.com/questions/18462064/associate-a-private-key-with-the-x509certificate2-class-in-net/24863777#24863777

**Comment by vtortola** [comment]
You got working WebSocketListener with SSL or just the SSL server example?

**Comment by AndyM84** [comment]
Yes sorry @vtortola, to be clear we got WebSocketListener working with WSS/TLS by using that method for loading the certificate from a file.

**Comment by vtortola** [comment]
Grand. I will add it to the documentation :+1:
