### ISSUE TITLE
message size limit

### ISSUE THREAD

**Issue by pashtetus1** [vtortola/WebSocketListener#72]
in my project I need to transfer a lot of data on a socket. how is limit the size of one message or how to find it? when i pass about 200kb message transfer lasts 800 ms, when i pass about 180kb message transfer lasts 0.5 ms . Why?

**Comment by vtortola** [comment]
There is no message limit enforced by the component, the protocol message limit is `UInt64.MaxValue`, and the default buffer is 8K. Make sure you dispose the `WebSocketMessageWriteStream` so that will flush the buffer once you are done writing the message.

**Comment by pashtetus1** [comment]
And if i using 
public static Task WriteStringAsync(this WebSocket ws, string data, CancellationToken cancel);
 It can be that something is wrong?
