### ISSUE TITLE
Using a random, system-assigned port

### ISSUE THREAD

**Issue by dobriai** [vtortola/WebSocketListener#73]
I need my `WebSocketListener` to bind and listen to "any available port" on my local host. So I  pass `IPEndPoint(IPAddress.Any, 0)` - that's fine. The problem is that the member `TcpListener _listener` is not public, so that I cannot do `((IPEndPoint)_server._listener.LocalEndpoint).Port` to get the actual port number being used.

I cannot think of a workaround other than exposing something from `_listener` - at least the `LocalEndpoint`.

Am I right that this will take a code change? If I am not, what else can I do? If I am, I'd be happy to work on a pull request, if necessary.

Best regards!

**Comment by vtortola** [comment]
Yes, probably exposing LocalEndpoint as a property of WebSocketListener will do .

**Comment by vtortola** [comment]
Addressed in https://github.com/vtortola/WebSocketListener/pull/74
