### ISSUE TITLE
Unobserved exception in WebSocketListener.StartAccepting

### ISSUE THREAD

**Issue by jacobs100500** [vtortola/WebSocketListener#88]
Server stops accepting new connections when thrown this exception. I was an exception - System.Net.Sockets.SocketException: Too many open files

**Comment by vtortola** [comment]
Are you sure you are disposing your connections correctly? That exception is thrown when lot of connections are opened and the system cannot open more.

**Comment by jacobs100500** [comment]
Yes. System cannot open more. I increased the number of connections (ulimit -n) and no longer throw an exception.

**Comment by vtortola** [comment]
Alright. Anyway check you are disposing the connections when the user disconnects and nothing is preventing the garbage collection.
