### ISSUE TITLE
Chrome Invalid frame header

### ISSUE THREAD

**Issue by freeger** [vtortola/WebSocketListener#89]
Hi, got error in chrome browser 'Invalid frame header' in Mono on Linux. Any ideas how to fix it? Very important for us. Thank you!

**Comment by vtortola** [comment]
Hi,

Which Mono version are you using?

Are you using compression? Different issues have been reported in the past about Mono:

 * Problems with compression:
  * https://github.com/vtortola/WebSocketListener/issues/69
  * https://github.com/vtortola/WebSocketListener/issues/83
 * An issue with `.ReadToEnd()` : https://github.com/vtortola/WebSocketListener/issues/54
 * And an issue with the Mono version: https://github.com/vtortola/WebSocketListener/issues/69

Are you getting any exception thrown at the server side?

Can you reproduce the error in isolation? I mean, can you produce a [Minimum Working Example](https://en.wikipedia.org/wiki/Minimal_Working_Example) I can work with?

**Comment by vtortola** [comment]
Try not to add the [`WebSocketDeflateExtension`](https://github.com/vtortola/WebSocketListener/wiki/Deflate-extension) and see if it works. Since Chrome is the only browser supporting websocket deflate compression, that could be the reason why the problem only happens with it.

**Comment by deniszykov** [comment]
Hi, we are not using any extensions (which are not active by default as far I know) and and the error occurs steadily in one place, where presumably large chunk(~1-3kb) of data is sent to the client. 

Error is reproduced only in Chrome. Unfortunately example for reproducing hard to recreate.
Mono JIT compiler version 4.2.2 (Stable 4.2.2.30/996df3c Mon Feb 15 17:30:30 UTC 2016)
vtortola/WebSocketListener vtortola.WebSocketListener.2.2.1.0

**Comment by vtortola** [comment]
Can you show me how are you sending that data to the client? It does not need to be the exact code, but at least, the exact methods and approach.

**Comment by deniszykov** [comment]
`
		public async Task SendMessageAsync(WebSocketMessage message, CancellationToken cancellation)
		{
			if (message.IsCloseMessage)
			{
				this.webSocket.Close();
			}
			else
			{
				// message.MessageType always Binary
				using (var writer = webSocket.CreateMessageWriter((WebSocketMessageType)message.MessageType))
				{
					// message.Content is MemoryStream
					await message.Content.WriteToAsync(writer, webSocketChannel.BufferSize, cancellation).ConfigureAwait(continueOnCapturedContext: false);
					await writer.CloseAsync(cancellation).ConfigureAwait(continueOnCapturedContext: false);
				}
			}
		}
`

**Comment by vtortola** [comment]
You mention Chrome, but have you tried this on other browser like Firefox or IE as well?

**Comment by freeger** [comment]
yes it works well at firefox (didnt try on ie)

**Comment by deniszykov** [comment]
Firefox and https://github.com/sta/websocket-sharp are fine.

**Comment by vtortola** [comment]
Using the Chrome dev tools, can you please copy and paste the HTTP request and response of the WebSocket connection?

**Comment by deniszykov** [comment]
http://take.ms/G3yOL 
http://take.ms/ZBlvj
Chrome: WebSocket has closed connection. Reason: [1006] 'Abnormal disconnection.

**Comment by vtortola** [comment]
Ok that is a different error. That error means the connection crashed without proper closing signaling. Probably an exception was thrown at the server side, can you see any in your logs?

**Comment by deniszykov** [comment]
Unfortunately there is no errors on server side (while sending response and checking IsConnected). Is there any special way to log internal errors in WebSocketListener?

**Comment by vtortola** [comment]
All errors are bubbled up, but if the exception happens after an `await`, it can become "unhandled". For example if you are running a given connection using `Task.Run`, since probably you are not awaiting the result, if there is an exception, it won't be handled. Make sure that whatever method you run in `Task.Run` has a try/catch that can log exceptions. The `1006` definitely means that the connection crashed, and it is not a code that WebSocketListener uses (since it is reserved to indicate the crash).

**Comment by deniszykov** [comment]
I found this error in server logs:
`Error: vtortola.WebSockets.WebSocketException: Cannot write on WebSocket ---> vtortola.WebSockets.WebSocketException: Write timeout
   at vtortola.WebSockets.Rfc6455.WebSocketConnectionRfc6455.<WriteInternalAsync>d__9.MoveNext()
   at vtortola.WebSockets.Rfc6455.WebSocketMessageWriteRfc6455Stream.<CloseAsync>d__6.MoveNext
`
But it's occurs after Chrome get 'Invalid frame header'. I logged payload size of "crashing frame". It's 73400 bytes long. Unfortunately I was not able to isolate the bug in small project. Maybe frequent two-way communication is a cause.

**Comment by vtortola** [comment]
The really intriguing thing is the fact it only happens in Chrome. 

Can you try to do the stream transfer asynchronously?:
```
using (var writer = webSocket.CreateMessageWriter((WebSocketMessageType)message.MessageType))
{
   message.Content.CopyTo(writer);
}
```
Make sure whatever `message` is, contains all the data you want to send. Also, set [PingTimeout](https://github.com/vtortola/WebSocketListener/wiki/WebSocketListener-options) to `Timeout.InfiniteTimeSpan`, just to make sure it is not the ping causing troubles.

**Comment by deniszykov** [comment]
Replaced to
```csharp
				var bytes = new byte[message.BodyLength.GetValueOrDefault()];
				message.Body.Read(bytes, 0, bytes.Length);
				uusing (var writer = webSocket.CreateMessageWriter((WebSocketMessageType)message.MessageType))
				{
					writer.Write(bytes, 0, bytes.Length);
				}
```
and got same error. Plus it's happens on .NET and localhost. I will try to dump all data and isolate it in small project.

**Comment by vtortola** [comment]
That would be fantastic.

**Comment by deniszykov** [comment]
It was really hard to re-create exact environment for this bug.
https://1drv.ms/u/s!ApDWfHMz85Utg59WQLvr5BR07mA0JA here is project

1) run project
2) open in Chrome http://localhost:8004/
3) open developer console 
4) press "Test"

I could share my clues about this bug if u want.

**Comment by vtortola** [comment]
Your send buffer set to 65535 hit the bug 😃   

65535 is indeed the [`UInt16.MaxValue`](https://msdn.microsoft.com/en-us/library/system.uint16.maxvalue(v=vs.110).aspx), however due the bug it was not considered as part of the [intermediate frame length](https://tools.ietf.org/html/rfc6455#section-5.2).

I think I have fixed it in https://github.com/vtortola/WebSocketListener/commit/cebb66f700db390eea3c4687add2a238394d3da4, however I need to do some more testing to be sure but please go ahead and try it. You can download latest DLL's from [AppVeyor](https://ci.appveyor.com/project/vtortola/websocketlistener/build/artifacts) If your testing and my testing goes well, tomorrow I can release a new Nuget package.

Many thanks for taking the time in reporting this and providing a MWE. I hope it was worth it 👍

**Comment by deniszykov** [comment]
Thanks, I will wait for Nuget package.

**Comment by freeger** [comment]
Hello Valeriano, how are you? Is there any news about Nuget package? Hope it helps with this issue

**Comment by vtortola** [comment]
Hi, I have been busy with some personal stuff. I have uploaded the new [Nuget package version 2.2.2.0](https://www.nuget.org/packages/vtortola.WebSocketListener/2.2.2).

**Comment by freeger** [comment]
Thnx a lot! 
Denis, could you please check this?

**Comment by freeger** [comment]
Thank you!
