### ISSUE TITLE
Message (byte) loss every 220 byte

### ISSUE THREAD

**Issue by mifwarior** [vtortola/WebSocketListener#90]
Sending 1 file from client(js) to server(c#) through websocket ( type = "arraybuffer");

Received file has difference every 220 byte, every 220 byte, byte equals 0;
How to configure the ws server. To avoid changes in data

log in WinDiff
Search for differences

1. C:\Projects\WebCAD\Server\bin\Debug\MEZZA.dwg: 397,774 bytes
2. C:\Users\yproskurin\Downloads\MEZZA.dwg: 397,774 bytes
Offsets: hexadec.

   DC:	00	1B
  3DC:	00	66
  7DC:	00	E2
  FDC:	00	E2
 1FDC:	00	E2
 3FDC:	00	E2
 7FDC:	00	E8
 FFDC:	00	BC
1FFDC:	00	03
3FFDC:	00	4B

10 difference(s) found. 

[MEZZA.zip](https://github.com/vtortola/WebSocketListener/files/529568/MEZZA.zip)

**Comment by vtortola** [comment]
Hi, 

Can you please provide a [Minimum Working Example](https://en.wikipedia.org/wiki/Minimal_Working_Example). That is, a very small project were the error can be observed and reproduced.

Cheers.

**Comment by mifwarior** [comment]
Hi, in minimum working example all works correctly. I found issue in js serialization. Thanks for the tip, this is not a bug websocket server
