### ISSUE TITLE
Synchronous methods calling in asynchronous methods

### ISSUE THREAD

**Issue by jacobs100500** [vtortola/WebSocketListener#91]
I found that method WebSocket.ReadMessageAsync using synchronous methods. All this is happening in class WebSocketConnectionRfc6455.
For example: WebSocketRfc6455.ReadMessageAsync -> WebSocketConnectionRfc6455.AwaitHeaderAsync -> ParseHeader -> TryReadHeaderUntil
TryReadHeaderUntil is a synchronous method with synchronous IO operations.
ProcessControlFrame also using a synchronous method this.WriteInternal()
If error using Close (synchronous method)

The method WriteInternalAsync using synchronous wait the semaphore _writeSemaphore.Wait(_options.WebSocketSendTimeout)

Ping loop also using a synchronous IO operations.

**Comment by vtortola** [comment]
Yes. Basically the component uses async when it is not sure if there is data in the buffer, but when there are certainty it uses sync methods.

**Comment by jacobs100500** [comment]
I started looking for this problem because the program used a lot of context switches and threads. I rewrote the code using asynchronous and it has reduced the use of 30% context switches and the number of threads to use. I have a web socket server is running at high load and it improved greatly helped.

**Comment by vtortola** [comment]
That is interesting. Did you measure it in a test app you can share? or you did it in your own app?

**Comment by jacobs100500** [comment]
I did it in my app. You can start performance test like [this](https://github.com/vtortola/WebSocketListener/wiki/WebSocketListener-performance-tests). My traffic consists of 20% of incoming messages and outgoing 80%. Also there is a connection/disconnection 1-5 per second. My program running in Mono. I watched statistics using Munin.

**Comment by vtortola** [comment]
I see. How big are those messages? any delay between message and message? are server and client running in the same machine?

**Comment by jacobs100500** [comment]
Most of the messages of size 300-400 bytes. Delay is very small - 0-100 ms. The server and client are on different machines. I tested it on real clients.

**Comment by vtortola** [comment]
Nice, thanks. I will try to replicate similar conditions when I have free time to see if I also experiment some improvement. Do you have any figure about how the performance was improved?

**Comment by jacobs100500** [comment]
Yes. http://rgho.st/6KnZzrlYh . In peak load are connected 6000 clients. November 3 was applied update. By the number of threads it has been revealed that the thread per client. After updating their number was reduced by almost half.

**Comment by Chelaris182** [comment]
@jacobs100500, feel free to take a look at https://github.com/vtortola/WebSocketListener/pull/75 https://github.com/vtortola/WebSocketListener/pull/76 https://github.com/vtortola/WebSocketListener/pull/77

**Comment by vtortola** [comment]
Fixed in 2.2.3
