### ISSUE TITLE
Server WebSocket OnClose

### ISSUE THREAD

**Issue by ellLazar** [vtortola/WebSocketListener#92]
.OnClose
how to handle the event WebSocket.OnClose,
where for some reason, it was disconnected from client
how to set this event ?
I did not found , in your docs, how to do it.

**Comment by vtortola** [comment]
Is not `.OnDisconnect` enough?

Cheers.

**Comment by ellLazar** [comment]
I tried ws.OnDisconnect ?
but there is no event to ws object
how is the syntax, to trigger events on ws object ?
I did not found it in your docs

**Comment by ellLazar** [comment]
ws instance remove from memory after disconnect ?
ws.Close ()
does it remove from memory Or I have to add :
 ws = null
 or: ws.Dispose()
