### ISSUE TITLE
Multiple messages sent in small timeframe (Question)

### ISSUE THREAD

**Issue by jonmaxwell** [vtortola/WebSocketListener#96]
I've created a websocket server using parts of the listener example code. My server is set up as a request/reply service where an incoming client message will invoke a method and the return data from that method is sent back to the client via **WriteStringAsync()**. 

The problem that I am having is that during some server method invocations, the method being called triggers a Broadcast event, where I loop through every connected client and send another message signalling that an action has been done.

Pseudocode example:

Client: [SendRequest]: Add(2,3)
Server: [ReceivedRequest]
Server: [Trigger Broadcast to all clients]: (2,3) has been added. Clients.ForEach(WriteStringAsync())
Server: [Add() finished] Send [5] response to calling client

It turns out that an exception is thrown on the server when sending the response the calling client. "Only one message can be sent at a time per client".

I've verified the client that called add() receives the broadcast while waiting for a response method, but doesn't receive the response message from the message it invoked. Is there a way I can check if the **WriteStringAsync** is currently in use, and wait to send until the the client is ready to send again?

Which should I use to only send one message at a time?

 await _internalWebsocket.WriteStringAsync(response, CancellationToken.None);
_internalWebsocket.WriteStringAsync(response, CancellationToken.None).Wait();

**Comment by deniszykov** [comment]
The WebSocket can send only one message at a time. You can use TPL Dataflow or custom solution based on some Queue to ensure this.

Here is example:
```csharp
var sendBlock = new ActionBlock<byte[]>(async messageBytes =>
{
	var isConnected = true;
	do
	{
		using (var writer = webSocket.CreateMessageWriter(WebSocketMessageType.Binary))
		{
			await writer.WriteAsync(messageBytes, 0, messageBytes.Length, CancellationToken.None).ConfigureAwait(continueOnCapturedContext: false);
			await writer.CloseAsync(CancellationToken.None).ConfigureAwait(continueOnCapturedContext: false);
		}

		isConnected = webSocket.IsConnected;
	} while (isConnected);

	throw new InvalidOperationException("WebSocket disconnected.");

}, new ExecutionDataflowBlockOptions { BoundedCapacity = DataflowBlockOptions.Unbounded, SingleProducerConstrained = true, TaskScheduler = TaskScheduler.Default });

// sending messages to WebSocket via ActionBlock
sendBlock.Post(new byte[999]);
```

**Comment by jonmaxwell** [comment]
Wow, thanks for the quick reply. From what I'm reading, if the writer is in use (only one message at a time) will the Post() block return false? Or does it automatically queue the message up.

So, if I check if sendBlock.Post() returns false, should I cache the message for later sending?

**Comment by deniszykov** [comment]
It automatically queue the messages and dispatch them sequentially. Post could return false when BoundedCapacity is set with some value. Also TPL Dataflow have [BroadcastBlock](https://msdn.microsoft.com/en-us/library/hh160447(v=vs.110).aspx)  which can be used to send messages to multiple blocks.

**Comment by vtortola** [comment]
Right. As with regular sockets, WSL was designed to work with only one concurrent thread for write, and another for reading. If you try to do concurrent writes or reads you will get into a unpredictable mess.

The best way of allowing multiple threads to send messages to the same connection, is to use the [producer consumer pattern](https://en.wikipedia.org/wiki/Producer%E2%80%93consumer_problem), which would allow to have multiple producers and just one consumer which would do the actual write in the socket. Just make sure that each element the consumer sends is a complete message, because the WebSocket protocol do not allows to interleave frames from different messages.

The most practical way of using producer/consumer in .NET with asyn/await support is TPL Dataflow as @deniszykov  has pointed out: http://blog.stephencleary.com/2012/11/async-producerconsumer-queue-using.html

**Comment by jonmaxwell** [comment]
This is really great stuff! I've been handling my broadcasts and message sending from the server in a very "basic way" (enough that it works). Now that my test application is handling a lot more remote invoke calls, I need to update the the code to utilize what TPL Dataflow offers!

Thanks again for the help @deniszykov and @vtortola.
